### ISSUE TITLE
"Application uses a database"

### ISSUE THREAD

**Issue by mclements** [vizziv/UrLib#1]
Thank you for the very nice library. As a bug report, when I use `library ../UrLib/Urlib` in the `.urp` file for another application, `urweb` gives an error:

> Application uses a database but has none configured with 'database' in .urp file.

I can avoid this error by (i) removing `user` from `lib.urp` or (ii) creating and using a database. For (ii), an SQLite database using the following SQL code may be sufficient:

`create table uw_User_users(uw_user,uw_pulse);`

Presumably any PostgreSQL `.sql` code would include appropriate types. Approach (i) would be a more portable solution.

Sincerely, Mark.

**Comment by vizziv** [comment]
What you point out is definitely a code smell. I just pushed a change to User that (1) should fix the problem and (2) I think is a better design. Thanks!

There is a larger question of this library being a grab bag of things at widely varying levels of abstraction. Probably Eq, Record, Subset, and some purely functional friends could be split off into a library separate from Pulse, User, and other abstractions built on top of databases. But I'm not maintaining this project very actively at the moment, and I don't see a pressing reason to decide on any partition right now.
